name: project_legion_build

on:
  # Triggered whenever push to the master branch
  push:
    branches:
      - main

  # Triggered whenever a pull request is created on master
  pull_request:
    branches: ["main"]
    types: [edited]


jobs:
  build:
    # Create a container of the latest Ubuntu, other values could be
    # ubuntu-latest, ubuntu-22.04, etc.
    runs-on: ubuntu-22.04

    steps:
      
      # Install some system pacakges
      - name: Install ROS 2 Humble packages
        run: |
          sudo apt update
          sudo apt install -y software-properties-common
          sudo add-apt-repository universe
          sudo apt update && sudo apt install -y curl
          sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
          sudo apt update
          sudo apt install -y ros-humble-ros-base python3-colcon-common-extensions
          sudo apt install -y lcov

      - name: Setup Workspace
        run: |
          source /opt/ros/humble/setup.bash
          mkdir -p ros_ws/src/project_legion
          cd ros_ws
          colcon build
          source install/setup.bash

      # We want to use GitHub CI checkout version 3 for checking out the branch
      - uses: actions/checkout@v3
        with:
          path: ros_ws/src/project_legion

      # Build for test coverage
      - name: Configure CMake flags and build exectables
        run: |
          source /opt/ros/humble/setup.bash
          sudo apt install python3-rosdep
          sudo rosdep init
          rosdep update --include-eol-distros
          cd ros_ws
          rosdep install --from-paths src -y --ignore-src
          colcon build

  deploy:
    runs-on: ubuntu-22.04
    steps:
      # SOURCE 단계 - 저장소 Checkout
      - name: Checkout-source code
        uses: actions/checkout@v3

      # docker hub 로그인
      - name: Login docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # docker image 빌드
      - name: Build docker image
        run: |
          docker build -t edenlee94/ros2_ci .
          docker run -it edenlee94/ros2_ci /bin/bash
        
      # docker image push
      - name: Push docker image
        run: |
          container_id=$(docker ps -q | head -n 1)
          echo "The ID of the first running container is: $container_id"
          docker commit $container_id edenlee94/ros2_ci:first
        

      # docker hub 퍼블리시
      - name: Publish to docker hub
        run: docker push edenlee94/ros2_ci
